name: Build
run-name: ${{ github.actor }} compiling based on CMakeLists.txt
on: [push]
jobs:
  compile_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with: submodules: recursive
      - name: CMake Action
        uses: threeal/cmake-action@v1.3.0
      - name: Code coverage
        uses: threeal/gcovr-action@v1.0.0
