name: Build
run-name: ${{ github.actor }} compiling based on CMakeLists.txt
on: [push]
jobs:
  compile_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Tests
        run: |
          cmake -H. -B_build -DBUILD_TESTS=ON
          cmake --build _build
          cmake --build _build --target test -- ARGS=--verbose
      - name: npm install, make test-coverage
        run: |
          npm install
          make test-coverage
      - name: Code coverage
        uses: threeal/gcovr-action@v1.0.0
